# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / \
    Path(r"D:\projects\Github\Projects-work\SafeDrive_Advanced Driver Authentication System\2. Under SSIP program\General test programs\UI-UX\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def on_entry_click(event):
    """Function that gets called whenever the entry is clicked"""
    if entry_1.get() == 'Search artist, title, album':
        entry_1.delete(0, "end")  # delete all the text in the entry
        entry_1.insert(0, '')  # Insert blank for user input
        entry_1.config(fg='#000000')

def on_focusout(event):
    """Function that gets called whenever the entry loses focus"""
    if entry_1.get() == '':
        entry_1.insert(0, 'Search artist, title, album')
        entry_1.config(fg='#B4B4B4')

window = Tk()

window.geometry("1440x720")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=720,
    width=1440,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_rectangle(
    0.0,
    0.0,
    270.0,
    720.0,
    fill="#FFFFFF",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    60.0,
    619.0,
    image=image_image_1
)

canvas.create_text(
    84.0,
    609.0,
    anchor="nw",
    text="Logout",
    fill="#999999",
    font=("MontserratRoman Medium", 16 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    58.0,
    565.0,
    image=image_image_2
)

canvas.create_text(
    80.0,
    555.0,
    anchor="nw",
    text="Account",
    fill="#999999",
    font=("MontserratRoman Medium", 16 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    58.0,
    511.0,
    image=image_image_3
)

canvas.create_text(
    80.0,
    501.0,
    anchor="nw",
    text="Setting",
    fill="#999999",
    font=("MontserratRoman Medium", 16 * -1)
)

canvas.create_text(
    24.0,
    447.0,
    anchor="nw",
    text="More",
    fill="#3C3E43",
    font=("MontserratRoman Bold", 16 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    58.0,
    392.0,
    image=image_image_4
)

canvas.create_text(
    80.0,
    382.0,
    anchor="nw",
    text="Audio Book",
    fill="#999999",
    font=("MontserratRoman Medium", 16 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    58.0,
    338.0,
    image=image_image_5
)

canvas.create_text(
    80.0,
    328.0,
    anchor="nw",
    text="Podcast",
    fill="#999999",
    font=("MontserratRoman Medium", 16 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    58.0,
    284.0,
    image=image_image_6
)

canvas.create_text(
    80.0,
    274.0,
    anchor="nw",
    text="Album ",
    fill="#999999",
    font=("MontserratRoman Medium", 16 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    58.0,
    230.0,
    image=image_image_7
)

canvas.create_text(
    80.0,
    220.0,
    anchor="nw",
    text="Artist",
    fill="#999999",
    font=("MontserratRoman Medium", 16 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    58.0,
    176.0,
    image=image_image_8
)

canvas.create_text(
    80.0,
    166.0,
    anchor="nw",
    text="Home",
    fill="#999999",
    font=("MontserratRoman SemiBold", 16 * -1)
)

canvas.create_text(
    24.0,
    108.0,
    anchor="nw",
    text="Discover",
    fill="#3C3E43",
    font=("MontserratRoman Bold", 16 * -1)
)

canvas.create_text(
    67.33331298828125,
    35.0,
    anchor="nw",
    text="ErrorsOnly",
    fill="#000000",
    font=("Nova Round", 30 * -1)
)


image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    42.0,
    50.0,
    image=image_image_9
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1178.0,
    y=655.5,
    width=24.0,
    height=24.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=1222.0,
    y=655.5,
    width=24.0,
    height=24.0
)

canvas.create_rectangle(
    1266.0,
    665.5,
    1366.0,
    669.5,
    fill="#C4C4C4",
    outline="")

canvas.create_rectangle(
    1266.0,
    665.5,
    1336.0,
    669.5,
    fill="#7C74EE",
    outline="")

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1386.0,
    y=655.5,
    width=24.0,
    height=24.0
)

canvas.create_text(
    568.0,
    675.5,
    anchor="nw",
    text="1:29",
    fill="#121212",
    font=("MontserratRoman Medium", 16 * -1)
)

canvas.create_rectangle(
    609.0,
    683.5,
    1083.0,
    687.5,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    609.0,
    683.5,
    940.8000183105469,
    687.5,
    fill="#7C74EE",
    outline="")

canvas.create_text(
    1095.0,
    675.5,
    anchor="nw",
    text="4:24",
    fill="#121212",
    font=("MontserratRoman Medium", 16 * -1)
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=743.0,
    y=641.0,
    width=24.0,
    height=24.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=787.0,
    y=641.0,
    width=24.0,
    height=24.0
)

# button_image_6 = PhotoImage(
#     file=relative_to_assets("image_1000.png"))
# button_6 = canvas.create_image(
#     849.0,
#     653.0,
#     image=button_image_6
# )
button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=838.0,
    y=642.0,
    width=22.0,
    height=22.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=887.0,
    y=641.0,
    width=24.0,
    height=24.0
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=931.0,
    y=641.0,
    width=24.0,
    height=24.0
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    332.0,
    667.0,
    image=image_image_10
)

canvas.create_text(
    385.0,
    647.0,
    anchor="nw",
    text="Jiwa yang Bersedih",
    fill="#121212",
    font=("MontserratRoman Medium", 16 * -1)
)

canvas.create_text(
    385.0,
    671.0,
    anchor="nw",
    text="Ghea Indrawati",
    fill="#8E8E8E",
    font=("MontserratRoman Medium", 14 * -1)
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    330.0,
    59.0,
    image=image_image_11
)

canvas.create_text(
    354.0,
    49.0,
    anchor="nw",
    text="Search artist, title, album",
    fill="#B4B4B4",
    font=("Nova Round Medium", 16 * -1)
)

# Placeholder entry field
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    810.5,
    58.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    fg="#B4B4B4",  # Initial placeholder color
    highlightthickness=0
)
entry_1.insert(0, 'Search artist, title, album')  # Insert the placeholder text
entry_1.bind('<FocusIn>', on_entry_click)
entry_1.bind('<FocusOut>', on_focusout)
entry_1.place(
    x=314.0,
    y=35.0,
    width=993.0,
    height=46.0
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    1381.0,
    59.0,
    image=image_image_12
)

canvas.create_text(
    720.0,
    360.0,
    anchor="nw",
    text="HELLO WORLD !!!",
    fill="#000000",
    font=("Nova Round", 24 * -1)
)
window.resizable(False, False)
window.mainloop()
